### ISSUE TITLE
Fehler beim Starten

### ISSUE THREAD

**Issue by janKir** [prof-membrane/plugin.video.funkmediathek#5]
Beim Versuch, das Addon auf Kodi 17.6 auf dem Fire TV Stick zu starten, erscheint ein Fehler mit Hinweis auf die Log-Datei:

> 22:19:27.264 T:18446744072508260704   ERROR: GetDirectory - Error getting
22:19:30.451 T:18446744072514297216   ERROR: Previous line repeats 6 times.
22:19:30.454 T:18446744072514297216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:19:30.553 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fformats%2f%3fpage%3d0%26size%3d50
22:19:30.558 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fformats%2f%3fpage%3d0%26size%3d50) failed
22:19:33.489 T:18446744072500639896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:19:33.555 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fseries%2f%3fpage%3d0%26size%3d50
22:19:33.558 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fseries%2f%3fpage%3d0%26size%3d50) failed
22:19:36.844 T:18446744072521544488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:19:36.940 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fseries%2f%3fpage%3d0%26size%3d50
22:19:36.948 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fseries%2f%3fpage%3d0%26size%3d50) failed
22:19:56.863 T:18446744072498834624   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
22:19:57.980 T:18446744072514297216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 20, in main
                                                return listDir()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:19:58.062 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/
22:19:58.067 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/) failed
22:20:14.568 T:18446744072511222944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 20, in main
                                                return listDir()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:20:14.647 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/
22:20:14.650 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/) failed
22:20:23.807 T:18446744072511222944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 20, in main
                                                return listDir()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:20:23.877 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/
22:20:23.880 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/) failed
22:20:37.998 T:18446744072508260704   ERROR: GetDirectory - Error getting
22:20:53.253 T:18446744072498834624   ERROR: Previous line repeats 2 times.
22:20:53.254 T:18446744072498834624   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
22:20:54.042 T:18446744072515502024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 20, in main
                                                return listDir()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:20:54.140 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/
22:20:54.142 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/) failed
22:21:09.577 T:18446744072519052216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 20, in main
                                                return listDir()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:21:09.669 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/
22:21:09.672 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/) failed
22:21:22.627 T:18446744072498834624   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
22:21:25.167 T:18446744072528402392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 53, in <module>
                                                list()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in list
                                                l = modes.get(mode)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/default.py", line 28, in listDir
                                                return jsonParser.parse(params['url'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 17, in parse
                                                response = libMediathek.getUrl(url,header)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
22:21:25.252 T:18446744072498834624   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fseries%2f%3fpage%3d0%26size%3d50
22:21:25.254 T:18446744072498834624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/?mode=listDir&url=https%3a%2f%2fapi.funk.net%2fv1.0%2fcontent%2fseries%2f%3fpage%3d0%26size%3d50) failed

**Comment by prof-membrane** [comment]
Kann ich nicht nachvollziehen. Das Log ist unvollständig und ohne Debugmodus. Bei mir läuft es.

**Comment by janKir** [comment]
Okay, ich bin mir nicht sicher, was aus dem Log relevant ist, also hier nochmal komplett und mit Debugmodus.
Also der Fehler kommt nicht direkt beim Start, der Bildschirm mit Formate und Serien wird angezeigt. Aber sobald ich dann versuche, auf eines von beiden zu navigieren, tritt der Fehler auf.

[kodi.log](https://github.com/prof-membrane/plugin.video.funkmediathek/files/1551214/kodi.log)

**Comment by prof-membrane** [comment]
Das ist noch die alte Version Add-ons, dessen API eingestellt wurde. Entweder du installiert die neue Ausgabe über mein Repository, oder du wartest bis meine Änderungen im offiziellen Repo landen.
