### ISSUE TITLE
Crashes with http 404 error

### ISSUE THREAD

**Issue by gldhnchn** [prof-membrane/plugin.video.funkmediathek#9]
When starting Funk Mediathek, it immediately crashes. 

- Funk Mediathek v1.5.0, installed from repository membrane https://github.com/prof-membrane/repository.membrane/wiki
- Nexx Video API service module v1.2.0
- libmediathek3 v1.5.0

logfile:
```
2019-07-22 20:49:51.037 T:939320032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.funkmediathek/default.py", line 50, in <module>
                                                list()
                                              File "/home/osmc/.kodi/addons/plugin.video.funkmediathek/default.py", line 47, in list
                                                l = modes.get(mode)()
                                              File "/home/osmc/.kodi/addons/plugin.video.funkmediathek/default.py", line 9, in main
                                                return jsonParser.parseMain()
                                              File "/home/osmc/.kodi/addons/plugin.video.funkmediathek/resources/lib/jsonparser.py", line 29, in parseMain
                                                response = libMediathek.getUrl(base+'/content/channels/?size=100',header)
                                              File "/home/osmc/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 34, in getUrl
                                                return _request(url,headers,post,cookies)
                                              File "/home/osmc/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 82, in _request
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
2019-07-22 20:49:51.058 T:951902944   ERROR: GetDirectory - Error getting plugin://plugin.video.funkmediathek/
2019-07-22 20:49:51.059 T:1915590192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funkmediathek/) failed
```

**Comment by Lazalatin** [comment]
This repository seems to be abandoned. Jugding from the [Kodi forums](https://forum.kodi.tv/showthread.php?tid=303100) it is now maintained by @sarbes. You can report the issue, if you still experience it, here: https://github.com/sarbes/plugin.video.funkmediathek/issues
